# Generated by Django 5.1.3 on 2024-11-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
