# Generated by Django 5.1.3 on 2024-11-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_product_prod_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_num', models.IntegerField(max_length=10)),
                ('stud_name', models.CharField(max_length=100)),
                ('stud_course', models.CharField(max_length=100)),
            ],
        ),
    ]
