# Generated by Django 5.1.3 on 2024-11-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_newentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newentry',
            old_name='reg_num',
            new_name='reg_reg',
        ),
    ]
